### ISSUE TITLE
[Challenge 3] Musterlösung unvollständig

### ISSUE THREAD

**Issue by DiskyToy** [IoT-Lab-FH-OOE/IoT-Hacking-Challenges#3]
Die [Musterlösung](https://github.com/IoT-Lab-FH-OOE/IoT-Hacking-Challenges/tree/main/Challenge%203%20-%20Firmware%20Analyse/Musterl%C3%B6sung) der Challenge 3 hört abrupt auf. Es scheint als wäre hier ein unvollständiges Dokument hochgeladen worden.

**Comment by frankthetank-music** [comment]
Habe die Musterlösung mit dem Text aus der Masterarbeit aktualisiert (a9b29ff)

Manche Teile des Repos sind scheinbar leider nicht aktuell, die vollständige und korrekte Doku ist allerdings in der Masterarbeit zu finden. Im Zweifelsfall bitte dort nachschlagen. Ich werde versuchen möglichst rasch das gesamte Repo nochmal durchzuschauen und basierend auf der Masterarbeit zu aktualisieren.

**Comment by frankthetank-music** [comment]
Habe die Musterlösung mit dem Text aus der Masterarbeit aktualisiert (a9b29ff)

Manche Teile des Repos sind scheinbar leider nicht aktuell, die vollständige und korrekte Doku ist allerdings in der Masterarbeit zu finden. Im Zweifelsfall bitte dort nachschlagen. Ich werde versuchen möglichst rasch das gesamte Repo nochmal durchzuschauen und basierend auf der Masterarbeit zu aktualisieren.
